meta-lxatac-software: labgrid: allow overriding USB ports in userconfig
linux-automation/meta-lxatac pull request #14
Opened 2023-02-16 10:56 UTC by hnez

This should make it easier to attach USB hubs to the TAC and getting the matches right.

I'm not too experienced with jinja2 so I've had some trouble working around the scoping rules (`set`ing a variable in a `include`d file does not have an effect on the file that did the `include`ing, but modifing the variable in another way does).
And preventing the output from my `usb_ports.pop` and `.extend` tricks from being rendered (that's what the `and '' and `or ''` are for).
Maybe you have some better idea.

@a3f could this be of any use to you?

2023-02-21 13:43 UTC, SmithChart approved these changes

2023-02-21 13:59 UTC, jluebbe requested changes
Looks good otherwise.

2023-02-21 14:41 UTC, jluebbe approved these changes

2023-02-22 08:46 UTC, SmithChart approved these changes

2023-02-22 10:25 UTC, merged