Update to Yocto 5.1 - Styhead
linux-automation/meta-lxatac pull request #189
Opened 2024-10-04 09:49 UTC by hnez

This updates meta-lxatac to the yocto styhead release.

TODO before merging:

- [ ] Wait for styhead to be released
- [ ] Fix some of the `TODO` in the commit messages

2025-04-28 09:14 UTC, jluebbe requested changes

2025-04-28 09:14 UTC, jluebbe commented on meta-lxatac-software/conf/distro/tacos.conf
> +WARN_QA:append = "patch-status buildpaths"
Perhaps limit the change to our layers only? (see https://lists.yoctoproject.org/g/yocto/message/63480)

2025-04-28 09:35 UTC, hnez commented on meta-lxatac-software/conf/distro/tacos.conf
> +WARN_QA:append = "patch-status buildpaths"
Makes sense. I've changed the respective lines.

2025-04-28 09:39 UTC, jluebbe commented on meta-lxatac-software/conf/distro/tacos.conf
> +WARN_QA:append = "patch-status buildpaths"
Hmm, shouldn't they be in the respective layer confs? @ejoerns

2025-04-28 09:52 UTC, ejoerns commented on meta-lxatac-software/conf/distro/tacos.conf
> +WARN_QA:append = "patch-status buildpaths"
I'd say so. Like https://web.git.yoctoproject.org/meta-arm/commit/?id=e867b0aa6a831c74cf50d23c25a74b68137bc9c3

(and with a leading space when using `append` syntax).

2025-04-28 11:27 UTC, hnez commented on meta-lxatac-software/conf/distro/tacos.conf
> +WARN_QA:append = "patch-status buildpaths"
Sounds good. I've changed the layer configs accordingly.

2025-04-28 12:48 UTC, hnez commented on meta-lxatac-software/conf/distro/tacos.conf
> +WARN_QA:append = "patch-status buildpaths"
The `barebox` build failed on the walnascar branch with the config moved to the layer configs, possibly because the barebox recipe itself is part of meta-oe there.
I've given up now and have just added Upstream-Stati everywhere and removed the `ERROR_QA:remove` / `WARN_QA:append`.

I don't know which recipe required the `buildpaths` exception, but I guess the CI will tell me soon.
I will update the respective recipe then.

2025-04-29 10:09 UTC, hnez commented on meta-lxatac-software/conf/distro/tacos.conf
> +WARN_QA:append = "patch-status buildpaths"
> I don't know which recipe required the `buildpaths` exception, but I guess the CI will tell me soon.

Looks like it was not required after all. I think we are good here.

2025-04-29 12:09 UTC, jluebbe approved these changes

2025-04-30 06:19 UTC, merged