Use a keyring directory for RAUC and add a devel certificate
linux-automation/meta-lxatac pull request #37
Opened 2023-04-06 10:45 UTC by hnez

Adding a devel certificate that is deployed (but not enabled) on all LXA TAC images makes it easier for newcomers to build and install their first custom bundle.

The install-time detection of which certificates to trust is required for our planned release channels for official bundles:

First the bundles are built and signed with the `rauc-devel.key.pem` key and tested on hardware.
If the tests are passed the existing bundle will be automatically re-signed with the nightly release key.
If a new stable release is to be released an existing nightly bundle that has been manually tested is manually re-signed with the stable release key.

All of these bundles are deployed with the same `/etc/rauc/certificates-*` but a stable bundle should only be able to install other stable bundles, so we need to detect the release channel the bundle belongs to at install-time.

2023-04-20 07:16 UTC, hnez commented
We are about to generate certificates for our release channels. I think we should include those in this PR before merging it.

2023-04-20 12:49 UTC, hnez commented
The PR now contains the newly generated certificates and should be ready for merging.

2023-05-25 09:15 UTC, jluebbe requested changes
Looks good otherwise.

2023-05-25 09:15 UTC, jluebbe commented on meta-lxatac-bsp/recipes-core/rauc/rauc_%.bbappend
> +    # Enable the certificate this bundle was signed with.
What do you mean by "this bundle", especially for images not installed via RAUC? Perhaps:
```suggestion
    # Enable the certificate this image was built with.
```

2023-05-25 09:15 UTC, jluebbe commented on meta-lxatac-software/recipes-core/bundles/files/hook.sh
> +			if [ "${slot_hash}" == "${cert_hash}" ]; then
It's not a per *slot* hash, but for the bundle signature. Perhaps?
```suggestion
		for bundle_hash in ${RAUC_BUNDLE_SPKI_HASHES}; do
			if [ "${bundle_hash}" == "${cert_hash}" ]; then
```

2023-06-13 15:19 UTC, Emantor approved these changes

2023-06-14 04:53 UTC, merged